version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/data/elasticsearch/data

  app:
    build: .
    container_name: boss_zhipin_app
    depends_on:
      - elasticsearch
    ports:
      - "8088:8088"
    volumes:
      - .:/app

volumes:
  esdata:
    driver: local
